"use client";

import { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";

// ─── Types & Constants ───────────────────────────────────────────────────────

type Phase = "idle" | "step1" | "step2" | "step3" | "streaming" | "done";
type InvStatus = "LOW" | "REORDER" | "OK" | "EXCESS";

const ASINS = [
  { name: "Vitamin C Serum 30ml", revenue: 16200, margin: 62, bsr: 1847 },
  { name: "Retinol Night Cream",   revenue: 11200, margin: 48, bsr: 3204 },
  { name: "Hyaluronic Acid Serum", revenue: 8100,  margin: 51, bsr: 4821 },
  { name: "Niacinamide Toner",     revenue: 6500,  margin: 44, bsr: 6230 },
  { name: "Collagen Eye Cream",    revenue: 5700,  margin: 56, bsr: 7814 },
];

const INVENTORY: { name: string; days: number; status: InvStatus }[] = [
  { name: "Hyaluronic Acid Serum", days: 27,  status: "LOW" },
  { name: "Vitamin C Serum 30ml",  days: 32,  status: "REORDER" },
  { name: "Retinol Night Cream",   days: 61,  status: "OK" },
  { name: "Niacinamide Toner",     days: 94,  status: "OK" },
  { name: "Collagen Eye Cream",    days: 242, status: "EXCESS" },
];

const INV_STYLE: Record<InvStatus, { dot: string; badge: string; label: string }> = {
  LOW:     { dot: "bg-red-500",    badge: "bg-red-500/15 text-red-400 border-red-500/30",    label: "URGENT" },
  REORDER: { dot: "bg-amber-400",  badge: "bg-amber-400/15 text-amber-400 border-amber-400/30", label: "REORDER" },
  OK:      { dot: "bg-emerald-500",badge: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30", label: "OK" },
  EXCESS:  { dot: "bg-sky-400",    badge: "bg-sky-400/15 text-sky-400 border-sky-400/30",    label: "EXCESS" },
};

const STEPS = [
  {
    id: "step1",
    skill: "AmazonDataReader",
    desc: "Connects to MCP database, normalizes Seller Central exports into typed JSON",
    log: [
      "→ Fetching sales data for Apr 1–7…",
      "→ Parsing 1,247 order records…",
      "→ Aggregating PPC campaign data…",
      "✓ 5 ASINs normalized, inventory mapped",
    ],
  },
  {
    id: "step2",
    skill: "BrandVoice",
    desc: "Applies TerraGlow tone, terminology, and formatting rules",
    log: [
      "→ Loading TerraGlow brand profile…",
      "→ Applying direct, data-first tone…",
      "✓ Voice rules active across all outputs",
    ],
  },
  {
    id: "step3",
    skill: "WeeklyReportGenerator",
    desc: "Composes executive summary, KPIs, action items, and ad insights",
    log: [
      "→ Generating executive summary…",
      "→ Scoring KPIs against targets…",
      "→ Identifying action items by urgency…",
      "→ Writing ad keyword recommendations…",
      "✓ Report ready — 847 words",
    ],
  },
];

const STEP_DURATION = [1800, 1200, 2000]; // ms per step

const REPORT = `WEEKLY PERFORMANCE REPORT
TerraGlow Skincare  ·  Apr 1–7, 2026
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EXECUTIVE SUMMARY

Revenue climbed 12.3% week-over-week
to $47,832 — outpacing last week's
8.1% growth rate. ACoS held at 28.6%,
inside your 30% target. Two SKUs need
immediate attention: Hyaluronic Acid
(27-day cover) is in the danger zone,
and Collagen Eye Cream (242 days) is
tying up working capital.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
KPI SCORECARD

  Revenue   $47,832  ↑12.3%  ● STRONG
  Units     1,247    ↑9.1%   ● STRONG
  AOV       $38.36   ↑2.9%   ● HEALTHY
  ACoS      28.6%    <30%    ● ON TARGET
  TACoS     8.8%     <10%    ● HEALTHY
  ROAS      3.50×    >3.0×   ● STRONG

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TOP PERFORMER

Vitamin C Serum 30ml
$16,200 revenue · 62% margin · BSR #1,847

At current ROAS of 3.50×, each extra
$100 in spend returns $350. BSR is
trending down — ranking momentum is
building. Increase daily ad budget
by 20% before the weekend window.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ACTION ITEMS

🔴  URGENT — Hyaluronic Acid Serum
    27 days of cover remaining.
    Reorder 500 units by Apr 10 or
    face stockout ~Apr 28. Out-of-
    stock cost: ~$290/day in lost rev.

⚠   Vitamin C Serum — Reorder now
    32 days of cover. Order 800 units
    to maintain a 60-day safety buffer.

⚠   Collagen Eye Cream — Excess stock
    242 days at risk. Run 15% coupon
    + Vine enrollment. Cut ad spend
    on this ASIN by 50% this week.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AD INSIGHTS

CPC dropped 8.2% — less competition.
Capture share now at lower cost.

CTR 0.42% vs. category avg 0.31% ↑
Impression share: 34% (room to grow)

Scale: "vitamin c serum face"
  ACoS 19.4% → raise bid +25%

Pause: "retinol cream anti aging"
  ACoS 61% → move budget to above

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by WeeklyReportGenerator
Claude Skills · TerraGlow workspace`;

// ─── Utility: format numbers ─────────────────────────────────────────────────

function fmt(n: number) {
  return n.toLocaleString("en-US");
}

// ─── Left Panel ──────────────────────────────────────────────────────────────

function LeftPanel() {
  return (
    <div className="flex flex-col gap-3 h-full overflow-y-auto pr-1 scrollbar-hide">
      {/* Client header */}
      <div className="flex items-center gap-2">
        <div className="w-7 h-7 rounded-md bg-emerald-500/20 border border-emerald-500/30 flex items-center justify-center text-xs">🌿</div>
        <div>
          <div className="text-[11px] font-semibold text-slate-200 leading-none">TerraGlow Skincare</div>
          <div className="text-[10px] text-slate-500 mt-0.5">Amazon Seller · Week of Apr 1–7, 2026</div>
        </div>
        <div className="ml-auto text-[9px] font-mono text-emerald-400 bg-emerald-400/10 border border-emerald-400/20 px-1.5 py-0.5 rounded">LIVE DATA</div>
      </div>

      {/* Revenue hero */}
      <div className="rounded-lg border border-white/7 bg-white/[0.03] p-3">
        <div className="text-[10px] text-slate-500 uppercase tracking-widest mb-1">Revenue</div>
        <div className="flex items-baseline gap-2">
          <span className="text-2xl font-bold font-mono text-slate-100">$47,832</span>
          <span className="text-xs font-mono text-emerald-400 bg-emerald-400/10 px-1.5 py-0.5 rounded">↑ 12.3% WoW</span>
        </div>
        <div className="flex gap-4 mt-2 pt-2 border-t border-white/5">
          <div>
            <div className="text-[9px] text-slate-600 uppercase tracking-wider">Units</div>
            <div className="text-sm font-mono text-slate-300">1,247</div>
          </div>
          <div>
            <div className="text-[9px] text-slate-600 uppercase tracking-wider">AOV</div>
            <div className="text-sm font-mono text-slate-300">$38.36</div>
          </div>
          <div>
            <div className="text-[9px] text-slate-600 uppercase tracking-wider">Orders</div>
            <div className="text-sm font-mono text-slate-300">1,247</div>
          </div>
        </div>
      </div>

      {/* Top ASINs */}
      <div className="rounded-lg border border-white/7 bg-white/[0.03] p-3">
        <div className="text-[10px] text-slate-500 uppercase tracking-widest mb-2">Top ASINs</div>
        <div className="space-y-1.5">
          {ASINS.map((a, i) => (
            <div key={a.name} className="flex items-center gap-2 py-1 border-b border-white/5 last:border-0">
              <span className="text-[10px] font-mono text-slate-600 w-3">{i + 1}</span>
              <div className="flex-1 min-w-0">
                <div className="text-[10px] text-slate-300 truncate">{a.name}</div>
                <div className="flex gap-2 mt-0.5">
                  <span className="text-[9px] font-mono text-slate-500">BSR #{fmt(a.bsr)}</span>
                  <span className="text-[9px] font-mono text-emerald-500">{a.margin}% margin</span>
                </div>
              </div>
              <div className="text-[10px] font-mono font-semibold text-slate-200">${(a.revenue / 1000).toFixed(1)}K</div>
            </div>
          ))}
        </div>
      </div>

      {/* PPC */}
      <div className="rounded-lg border border-white/7 bg-white/[0.03] p-3">
        <div className="text-[10px] text-slate-500 uppercase tracking-widest mb-2">PPC Performance</div>
        <div className="grid grid-cols-2 gap-2">
          {[
            { label: "Ad Spend",   value: "$4,231",  sub: null },
            { label: "Ad Revenue", value: "$14,809", sub: null },
            { label: "ACoS",       value: "28.6%",   sub: "target <30%", ok: true },
            { label: "ROAS",       value: "3.50×",   sub: "floor 3.0×",  ok: true },
            { label: "TACoS",      value: "8.8%",    sub: "target <10%", ok: true },
          ].map((m) => (
            <div key={m.label} className="bg-white/[0.02] rounded p-2">
              <div className="text-[9px] text-slate-600 uppercase tracking-wider">{m.label}</div>
              <div className="text-sm font-mono font-semibold text-slate-200">{m.value}</div>
              {m.sub && (
                <div className={`text-[9px] ${m.ok ? "text-emerald-500" : "text-slate-600"}`}>{m.sub}</div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Inventory */}
      <div className="rounded-lg border border-white/7 bg-white/[0.03] p-3">
        <div className="text-[10px] text-slate-500 uppercase tracking-widest mb-2">Inventory Status</div>
        <div className="space-y-1.5">
          {INVENTORY.map((inv) => {
            const s = INV_STYLE[inv.status];
            return (
              <div key={inv.name} className="flex items-center gap-2">
                <div className={`w-1.5 h-1.5 rounded-full flex-shrink-0 ${s.dot}`} />
                <div className="flex-1 text-[10px] text-slate-400 truncate">{inv.name}</div>
                <span className="text-[9px] font-mono text-slate-500">{inv.days}d</span>
                <span className={`text-[8px] font-mono px-1.5 py-0.5 rounded border ${s.badge}`}>{s.label}</span>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

// ─── Middle Pipeline Panel ───────────────────────────────────────────────────

function PipelinePanel({ phase, onGenerate }: { phase: Phase; onGenerate: () => void }) {
  // After step1 completes, step2 starts — so during step2, step0 is done
  function correctedState(i: number): "idle" | "active" | "done" {
    const phaseOrder = ["idle", "step1", "step2", "step3", "streaming", "done"];
    const current = phaseOrder.indexOf(phase);
    const stepStart = i + 1; // step1=1, step2=2, step3=3
    const stepEnd = i + 2;   // step1 ends when step2 starts
    if (current >= stepEnd || (current >= 4)) return "done"; // streaming(4)/done(5)
    if (current === stepStart) return "active";
    return "idle";
  }

  return (
    <div className="flex flex-col items-center gap-0 py-2">
      {/* Label */}
      <div className="text-[9px] font-mono uppercase tracking-[0.2em] text-slate-600 mb-4">Claude Skills</div>

      {STEPS.map((step, i) => {
        const state = correctedState(i);
        return (
          <div key={step.id} className="flex flex-col items-center">
            {/* Node */}
            <motion.div
              animate={{
                boxShadow: state === "active"
                  ? "0 0 0 1px rgba(99,102,241,0.6), 0 0 16px rgba(99,102,241,0.3)"
                  : state === "done"
                  ? "0 0 0 1px rgba(34,197,94,0.4)"
                  : "0 0 0 1px rgba(255,255,255,0.07)",
              }}
              className="w-40 rounded-lg p-2.5 bg-slate-900 relative"
            >
              {/* Status dot */}
              <div className="flex items-center gap-1.5 mb-1">
                <motion.div
                  animate={{
                    backgroundColor:
                      state === "active" ? "#6366f1" :
                      state === "done" ? "#22c55e" :
                      "#334155",
                    scale: state === "active" ? [1, 1.3, 1] : 1,
                  }}
                  transition={state === "active" ? { duration: 0.8, repeat: Infinity } : {}}
                  className="w-1.5 h-1.5 rounded-full flex-shrink-0"
                />
                <span className={`text-[9px] font-mono font-semibold ${
                  state === "active" ? "text-indigo-400" :
                  state === "done" ? "text-emerald-400" :
                  "text-slate-600"
                }`}>
                  {state === "done" ? "✓ DONE" : state === "active" ? "RUNNING" : "WAITING"}
                </span>
              </div>

              <div className={`text-[10px] font-semibold font-mono mb-0.5 ${
                state === "idle" ? "text-slate-600" : "text-slate-200"
              }`}>{step.skill}</div>
              <div className="text-[9px] text-slate-600 leading-relaxed">{step.desc}</div>

              {/* Log output */}
              <AnimatePresence>
                {state !== "idle" && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    className="mt-2 pt-2 border-t border-white/5 overflow-hidden"
                  >
                    {step.log.slice(0, state === "done" ? step.log.length : 2).map((line, li) => (
                      <motion.div
                        key={li}
                        initial={{ opacity: 0, x: -4 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: li * 0.15 }}
                        className={`text-[8px] font-mono leading-relaxed ${
                          line.startsWith("✓") ? "text-emerald-500" : "text-slate-500"
                        }`}
                      >
                        {line}
                      </motion.div>
                    ))}
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>

            {/* Connector */}
            {i < STEPS.length - 1 && (
              <div className="flex flex-col items-center my-1 gap-0.5">
                {[0, 1, 2].map((dot) => (
                  <motion.div
                    key={dot}
                    animate={{
                      backgroundColor:
                        correctedState(i) === "done" ? "#22c55e" :
                        correctedState(i) === "active" ? "#6366f1" :
                        "#1e293b",
                    }}
                    className="w-0.5 h-1 rounded-full"
                  />
                ))}
              </div>
            )}
          </div>
        );
      })}

      {/* Generate button */}
      <div className="mt-5 w-full px-1">
        <button
          onClick={onGenerate}
          disabled={phase !== "idle" && phase !== "done"}
          className="w-full py-2 rounded-lg text-[11px] font-semibold transition-all duration-300 disabled:cursor-not-allowed"
          style={
            phase === "idle" || phase === "done"
              ? {
                  background: "linear-gradient(135deg, #4f46e5, #7c3aed)",
                  color: "white",
                  boxShadow: "0 0 16px rgba(99,102,241,0.25)",
                }
              : {
                  background: "rgba(255,255,255,0.04)",
                  color: "#475569",
                  border: "1px solid rgba(255,255,255,0.07)",
                }
          }
        >
          {phase === "idle" ? "Generate Report →" :
           phase === "done" ? "Regenerate →" :
           phase === "streaming" ? "Writing…" :
           "Running skills…"}
        </button>
      </div>

      {/* Footer note */}
      <div className="mt-3 text-[8px] text-slate-700 text-center leading-relaxed font-mono">
        AmazonDataReader + BrandVoice<br />
        + WeeklyReportGenerator
      </div>
    </div>
  );
}

// ─── Right Panel ─────────────────────────────────────────────────────────────

function RightPanel({ phase, text }: { phase: Phase; text: string }) {
  const isEmpty = phase === "idle";

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center justify-between mb-3">
        <div className="text-[10px] text-slate-500 uppercase tracking-widest">Generated Report</div>
        <AnimatePresence>
          {phase === "done" && (
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              className="text-[9px] font-mono text-emerald-400 bg-emerald-400/10 border border-emerald-400/20 px-2 py-0.5 rounded"
            >
              ✓ Complete · 847 words
            </motion.div>
          )}
          {(phase === "step3" || phase === "streaming") && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="text-[9px] font-mono text-indigo-400 bg-indigo-400/10 border border-indigo-400/20 px-2 py-0.5 rounded"
            >
              ● Writing
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Terminal */}
      <div className="flex-1 rounded-lg border border-white/7 bg-black/40 overflow-hidden flex flex-col">
        {/* Traffic lights */}
        <div className="flex items-center gap-1.5 px-3 py-2 border-b border-white/5 bg-white/[0.02]">
          <div className="w-2 h-2 rounded-full bg-red-500/50" />
          <div className="w-2 h-2 rounded-full bg-amber-400/50" />
          <div className="w-2 h-2 rounded-full bg-emerald-500/50" />
          <span className="ml-2 text-[9px] font-mono text-slate-600">weekly-report.txt</span>
        </div>

        {/* Content */}
        <div className="flex-1 p-3 overflow-y-auto scrollbar-hide">
          {isEmpty ? (
            <div className="h-full flex flex-col items-center justify-center gap-3 opacity-30">
              <div className="text-3xl">📄</div>
              <div className="text-[10px] font-mono text-slate-500 text-center">
                Click Generate Report<br />to run the skills pipeline
              </div>
            </div>
          ) : (
            <pre className="text-[10px] font-mono text-slate-300 leading-relaxed whitespace-pre-wrap break-words">
              {text}
              {(phase === "streaming") && (
                <motion.span
                  animate={{ opacity: [1, 0] }}
                  transition={{ duration: 0.5, repeat: Infinity }}
                  className="inline-block w-[6px] h-[11px] bg-indigo-400 ml-0.5 align-middle"
                />
              )}
            </pre>
          )}
        </div>
      </div>
    </div>
  );
}

// ─── Main Page ───────────────────────────────────────────────────────────────

export default function ClaudeSkillsArchitecturePage() {
  const [phase, setPhase] = useState<Phase>("idle");
  const [displayedText, setDisplayedText] = useState("");
  const streamRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const timeoutsRef = useRef<ReturnType<typeof setTimeout>[]>([]);

  function clearAll() {
    if (streamRef.current) clearInterval(streamRef.current);
    timeoutsRef.current.forEach(clearTimeout);
    timeoutsRef.current = [];
  }

  function generate() {
    clearAll();
    setDisplayedText("");
    setPhase("step1");

    const t1 = setTimeout(() => {
      setPhase("step2");
      const t2 = setTimeout(() => {
        setPhase("step3");
        const t3 = setTimeout(() => {
          setPhase("streaming");
          let idx = 0;
          streamRef.current = setInterval(() => {
            idx += 4;
            setDisplayedText(REPORT.slice(0, idx));
            if (idx >= REPORT.length) {
              clearInterval(streamRef.current!);
              setDisplayedText(REPORT);
              setPhase("done");
            }
          }, 18);
        }, STEP_DURATION[2]);
        timeoutsRef.current.push(t3);
      }, STEP_DURATION[1]);
      timeoutsRef.current.push(t2);
    }, STEP_DURATION[0]);
    timeoutsRef.current.push(t1);
  }

  useEffect(() => () => clearAll(), []);

  return (
    <div
      className="min-h-screen text-slate-100 overflow-hidden"
      style={{ background: "#08091a" }}
    >
      {/* Subtle dot-grid bg */}
      <div
        className="fixed inset-0 pointer-events-none"
        style={{
          backgroundImage: "radial-gradient(circle, rgba(255,255,255,0.04) 1px, transparent 1px)",
          backgroundSize: "28px 28px",
          maskImage: "radial-gradient(ellipse 80% 80% at 50% 50%, black, transparent)",
        }}
      />

      {/* Page wrapper */}
      <div className="relative z-10 flex flex-col min-h-screen max-w-7xl mx-auto px-4 py-6">

        {/* Top bar */}
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <div
              className="w-8 h-8 rounded-lg flex items-center justify-center text-sm"
              style={{ background: "linear-gradient(135deg, #4f46e5, #7c3aed)" }}
            >
              🧠
            </div>
            <div>
              <div className="text-sm font-semibold text-slate-100">Claude Skills Architecture</div>
              <div className="text-[10px] text-slate-500">Amazon data → AI skills → weekly report</div>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <div className="text-[9px] font-mono text-slate-600">built for</div>
            <div className="text-[9px] font-mono text-slate-400 border border-white/7 px-2 py-1 rounded">
              Claude AI Consultant · Upwork
            </div>
            <a
              href="/"
              className="text-[10px] text-slate-600 hover:text-slate-400 transition-colors ml-2"
            >
              ← portfolio
            </a>
          </div>
        </div>

        {/* Column labels */}
        <div className="grid grid-cols-1 lg:grid-cols-[1fr_180px_1fr] gap-4 mb-2">
          <div className="text-[9px] font-mono uppercase tracking-widest text-slate-700">
            01 · Raw Amazon Data
          </div>
          <div className="hidden lg:block text-[9px] font-mono uppercase tracking-widest text-slate-700 text-center">
            02 · Skills Pipeline
          </div>
          <div className="hidden lg:block text-[9px] font-mono uppercase tracking-widest text-slate-700">
            03 · Generated Output
          </div>
        </div>

        {/* Three panels */}
        <div className="grid grid-cols-1 lg:grid-cols-[1fr_180px_1fr] gap-4 flex-1">
          {/* Left */}
          <motion.div
            initial={{ opacity: 0, x: -16 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5 }}
            className="min-h-0"
          >
            <LeftPanel />
          </motion.div>

          {/* Middle */}
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="rounded-xl border border-white/7 bg-white/[0.02] px-3 py-4"
          >
            <PipelinePanel phase={phase} onGenerate={generate} />
          </motion.div>

          {/* Right */}
          <motion.div
            initial={{ opacity: 0, x: 16 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="min-h-[500px] lg:min-h-0"
          >
            <RightPanel phase={phase} text={displayedText} />
          </motion.div>
        </div>

        {/* Footer */}
        <div className="mt-6 flex items-center justify-between text-[9px] font-mono text-slate-700">
          <div>
            Architecture used in Atlas — 21-tool AI platform · $300K+/month operations
          </div>
          <div>
            Session 1: Foundation · Session 2: Composites · Session 3: Outputs + Cowork
          </div>
        </div>
      </div>
    </div>
  );
}
